# Generated by Django 5.2.3 on 2025-09-19 10:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampMondial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('description', models.TextField()),
                ('renfort_national', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='camps/')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='CategorieMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Catégorie de Matériel',
                'verbose_name_plural': 'Catégories de Matériels',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
            },
        ),
        migrations.CreateModel(
            name='DemandePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_demande', models.CharField(editable=False, max_length=100)),
                ('raison', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de Permission',
                'verbose_name_plural': 'Demandes de Permission',
            },
        ),
        migrations.CreateModel(
            name='Eglise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(auto_created=True, blank=True, default='logo_ebng.png', error_messages={'error': 'Le chemin vers le logo est requis.'}, null=True, upload_to='logos_eglises/')),
                ('nom', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='eglises/')),
                ('pays', models.CharField(blank=True, default="Côte d'Ivoire", max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, max_length=9, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=9, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('pasteur', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasteur_eglise', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_eglise', to='logistque.region')),
            ],
            options={
                'verbose_name': 'Eglise',
                'verbose_name_plural': 'Eglises',
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'événement")),
                ('type_evenement', models.CharField(choices=[('seminaire', 'Séminaire'), ('conference', 'Conférence'), ('culte', 'Culte Spécial'), ('concert', 'Concert'), ('camp', 'Camp Mondial'), ('autre', 'Autre')], max_length=20, verbose_name="Type d'événement")),
                ('organisateur_type', models.CharField(blank=True, choices=[('eglise', 'Église'), ('externe', 'Entité Externe')], max_length=20, null=True, verbose_name="Type d'organisateur")),
                ('lieu', models.CharField(blank=True, max_length=200, null=True, verbose_name="Lieu de l'événement")),
                ('organisateur_nom', models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'organisateur")),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de fin')),
                ('formatted_date_debut', models.CharField(blank=True, max_length=100, null=True, verbose_name='Date de début formatée')),
                ('formatted_date_fin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Date de fin formatée')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('chronogramme', models.JSONField(blank=True, default=list, verbose_name='Programme détaillé (JSON)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/', verbose_name="Image de l'événement")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20, verbose_name="Statut de l'événement")),
                ('eglise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistque.eglise', verbose_name='Église concernée')),
                ('logisticiens_gestion', models.ManyToManyField(blank=True, related_name='evenements_logisticiens', to=settings.AUTH_USER_MODEL, verbose_name='Logisticiens assignés')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='FormationLogisticien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_form', models.DateField(auto_now_add=True)),
                ('est_forme', models.BooleanField(default=False)),
                ('remarque', models.TextField(blank=True)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='logistque.eglise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formation_logisticien', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formation Logisticien',
                'verbose_name_plural': 'Formations Logisticiens',
            },
        ),
        migrations.CreateModel(
            name='Logistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eglise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistique_eglise', to='logistque.eglise')),
                ('responsable', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_logistique', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logistique',
                'verbose_name_plural': 'Logistiques',
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materiels/', verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimer')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code')),
                ('code_barre', models.ImageField(blank=True, null=True, upload_to='barcodes/', verbose_name='Code Barre')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de Création')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels_categorie', to='logistque.categoriemateriel', verbose_name='Catégorie')),
                ('eglise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiels_eglise', to='logistque.eglise', verbose_name='Eglise')),
                ('logistique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels_logistique', to='logistque.logistique', verbose_name='Logistique')),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='EvenementMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(blank=True, default=1, help_text="Quantité de matériel utilisée pour l'événement", null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(blank=True, help_text='Utilisateur qui a ajouté le matériel', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('evenement', models.ForeignKey(blank=True, help_text='Événement auquel le matériel est associé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiels_associes', to='logistque.evenement', verbose_name='Événement')),
                ('materiel', models.ForeignKey(blank=True, help_text="Matériel utilisé pour l'événement", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenements_associes', to='logistque.materiel', verbose_name='Matériel')),
            ],
            options={
                'verbose_name': 'Matériel utilisé pour événement',
                'verbose_name_plural': 'Matériels utilisés pour événements',
                'ordering': ['-date_ajout'],
                'unique_together': {('evenement', 'materiel')},
            },
        ),
        migrations.AddField(
            model_name='evenement',
            name='materiels_utilises',
            field=models.ManyToManyField(blank=True, help_text='Matériels utilisés pour cet événement', related_name='evenements', through='logistque.EvenementMateriel', to='logistque.materiel', verbose_name='Matériels utilisés'),
        ),
        migrations.CreateModel(
            name='ChronogrammeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField(blank=True, help_text="Heure de début de l'activité", null=True, verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, help_text="Heure de fin de l'activité", null=True, verbose_name='Heure de fin')),
                ('titre', models.CharField(blank=True, help_text="Titre de l'activité (ex: 'Cérémonie d'ouverture')", max_length=100, null=True, verbose_name='Titre')),
                ('description', models.TextField(blank=True, help_text="Description détaillée de l'activité", null=True, verbose_name='Description')),
                ('responsable', models.CharField(blank=True, help_text='Personne en charge de cette activité', max_length=100, null=True, verbose_name='Responsable')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, null=True, verbose_name='Dernière modification')),
                ('cree_par', models.ForeignKey(blank=True, help_text='Utilisateur qui a créé cette activité', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('evenement', models.ForeignKey(blank=True, help_text='Événement auquel cet élément de chronogramme est associé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chronogramme_evenement', to='logistque.evenement', verbose_name='Événement')),
                ('materiels_needed', models.ManyToManyField(blank=True, help_text='Matériel nécessaire pour cette activité', related_name='chronogramme_items', to='logistque.materiel', verbose_name='Matériels nécessaires')),
            ],
            options={
                'verbose_name': 'Élément du chronogramme',
                'verbose_name_plural': 'Éléments du chronogramme',
                'ordering': ['heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='CampMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_utilisee', models.PositiveIntegerField()),
                ('date_utilisation', models.DateField(auto_now=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistque.campmondial')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistque.materiel')),
            ],
            options={
                'verbose_name': 'Matériel Utilisé',
                'verbose_name_plural': 'Matériels Utilisés',
            },
        ),
        migrations.CreateModel(
            name='MaterielImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materiel/images/', verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('materiel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_materiel', to='logistque.materiel', verbose_name='Matériel')),
            ],
            options={
                'verbose_name': 'Image de Matériel',
                'verbose_name_plural': 'Images de Matériels',
                'ordering': ['materiel'],
            },
        ),
        migrations.CreateModel(
            name='MembreLogistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logistique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistque.logistique')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre Logistique',
                'verbose_name_plural': 'Membres Logistique',
            },
        ),
        migrations.CreateModel(
            name='PhotosEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/photos/', verbose_name='Photo')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date d'ajout")),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='logistque.evenement', verbose_name='Événement')),
            ],
            options={
                'verbose_name': "Photo d'événement",
                'verbose_name_plural': "Photos d'événement",
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ReservationMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('date_reserver', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20, verbose_name='Statut de la réservation')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_evenement', to='logistque.evenement', verbose_name='Événement')),
                ('materiel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_materiel', to='logistque.materiel', verbose_name='Matériel')),
            ],
            options={
                'verbose_name': 'Réservation de Matériel',
                'verbose_name_plural': 'Réservations de Matériel',
            },
        ),
        migrations.CreateModel(
            name='SousCategorieMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistque.categoriemateriel', verbose_name='Sous-Catégorie')),
            ],
            options={
                'verbose_name': 'Sous-Catégorie de Matériel',
                'verbose_name_plural': 'Sous-Catégories de Matériels',
            },
        ),
        migrations.AddField(
            model_name='materiel',
            name='sous_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiels_sous_categorie', to='logistque.souscategoriemateriel', verbose_name='Sous-Catégorie'),
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistque.region')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
            },
        ),
        migrations.AddField(
            model_name='eglise',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville_eglise', to='logistque.ville'),
        ),
        migrations.AddField(
            model_name='campmondial',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistque.ville'),
        ),
        migrations.AddConstraint(
            model_name='evenement',
            constraint=models.UniqueConstraint(fields=('titre', 'date_debut'), name='unique_evenement_date'),
        ),
        migrations.AddConstraint(
            model_name='evenement',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__gt', models.F('date_debut'))), name='check_date_fin_apres_debut', violation_error_message='La date de fin doit être postérieure à la date de début'),
        ),
        migrations.AddConstraint(
            model_name='chronogrammeitem',
            constraint=models.CheckConstraint(condition=models.Q(('heure_fin__gt', models.F('heure_debut'))), name='check_heure_fin_apres_debut', violation_error_message="L'heure de fin doit être postérieure à l'heure de début"),
        ),
    ]
