# Generated by Django 5.2.3 on 2025-09-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistque', '0002_add_user_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
