# Generated by Django 5.2.3 on 2026-02-20 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistque', '0001_initial'),
    ]

    operations = []
