# Generated by Django 5.2.3 on 2025-09-26 18:16

from django.db import migrations, models
from django.utils import timezone

def set_default_created_at(apps, schema_editor):
    """Set default created_at for existing regions without a value"""
    Region = apps.get_model('logistque', 'Region')
    for region in Region.objects.filter(created_at__isnull=True):
        region.created_at = timezone.now()
        region.save()

class Migration(migrations.Migration):

    dependencies = [
        ('logistque', '0002_region_created_at'),
    ]

    operations = [
        migrations.RunPython(set_default_created_at),
        migrations.AlterField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
