# Generated by Django 5.2.3 on 2026-02-07 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistque', '0003_fix_region_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenementmateriel',
            options={'verbose_name': "Matériel d'événement", 'verbose_name_plural': "Matériels d'événement"},
        ),
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Expliquez pourquoi vous avez besoin de cette permission', verbose_name='Raison de la demande')),
                ('action_type', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression')], default='create', max_length=10, verbose_name="Type d'action")),
                ('materiel_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID du matériel (si applicable)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de révision')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name="Notes de l'administrateur")),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Révisé par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Demande de permission',
                'verbose_name_plural': 'Demandes de permission',
                'ordering': ['-created_at'],
            },
        ),
    ]
