# Generated by Django 5.2.3 on 2026-03-17 13:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistque', '0004_alter_evenementmateriel_options_permissionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoleCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pôle de Compétence',
                'verbose_name_plural': 'Pôles de Compétence',
            },
        ),
        migrations.AddField(
            model_name='eglise',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est active'),
        ),
        migrations.AddField(
            model_name='eglise',
            name='is_national_hq',
            field=models.BooleanField(default=False, verbose_name='Siège National'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='type_programme',
            field=models.CharField(choices=[('national', 'National'), ('local', 'Local')], default='local', max_length=10, verbose_name='Échelle du programme'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='etat',
            field=models.CharField(choices=[('OP', 'Opérationnel'), ('PA', 'En panne'), ('RE', 'En réparation'), ('PE', 'Perdu')], default='OP', max_length=2, verbose_name='État'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='identifiant_unique',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID Unique'),
        ),
        migrations.AlterField(
            model_name='chronogrammeitem',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Membre en charge de cette activité', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.CreateModel(
            name='DemandeFormationSGL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_souhaitee', models.DateField()),
                ('valide', models.BooleanField(default=False)),
                ('rll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_formation_envoyees_sgl', to=settings.AUTH_USER_MODEL)),
                ('rln', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_formation_recues_sgl', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de Formation (SGL)',
                'verbose_name_plural': 'Demandes de Formation (SGL)',
            },
        ),
        migrations.CreateModel(
            name='ExpressionBesoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liste_materiel', models.TextField(help_text='Liste du matériel à acheter ou louer')),
                ('estimation_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistque.eglise')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistque.evenement')),
            ],
            options={
                'verbose_name': 'Expression de Besoin',
                'verbose_name_plural': 'Expressions de Besoins',
            },
        ),
        migrations.CreateModel(
            name='FicheDefectuosite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description de la panne')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pannes/')),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('repare', models.BooleanField(default=False)),
                ('date_reparation', models.DateTimeField(blank=True, null=True)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_defectuosite', to='logistque.materiel')),
                ('rapporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiche de défectuosité',
                'verbose_name_plural': 'Fiches de défectuosité',
            },
        ),
        migrations.CreateModel(
            name='MouvementMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('IN', 'Entrée (Check-in)'), ('OUT', 'Sortie (Check-out)'), ('PRET', 'Prêt / Appui')], max_length=4)),
                ('quantite', models.PositiveIntegerField()),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('eglise_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_entrants', to='logistque.eglise')),
                ('eglise_origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_sortants', to='logistque.eglise')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistque.evenement')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='logistque.materiel')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de Matériel',
                'verbose_name_plural': 'Mouvements de Matériel',
            },
        ),
        migrations.AddField(
            model_name='chronogrammeitem',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistque.polecompetence', verbose_name='Pôle de compétence'),
        ),
        migrations.CreateModel(
            name='RessourceFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_ressource', models.CharField(choices=[('video', 'Vidéo'), ('pdf', 'Document PDF'), ('autre', 'Autre')], max_length=10)),
                ('lien_url', models.URLField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='formations/')),
                ('description', models.TextField(blank=True)),
                ('pole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistque.polecompetence')),
            ],
            options={
                'verbose_name': 'Ressource de Formation',
                'verbose_name_plural': 'Ressources de Formation',
            },
        ),
        migrations.CreateModel(
            name='ReunionDimanche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reunion', models.DateField(default=django.utils.timezone.now)),
                ('heure_debut', models.TimeField(default='20:00')),
                ('heure_fin', models.TimeField(default='21:30')),
                ('ordre_du_jour', models.TextField()),
                ('pv_reunion', models.TextField(blank=True, verbose_name='Procès-verbal')),
                ('eglise_hote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistque.eglise', verbose_name='Église Hôte')),
                ('participants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réunion du Dimanche',
                'verbose_name_plural': 'Réunions du Dimanche',
            },
        ),
        migrations.CreateModel(
            name='ValidationCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape_actuelle', models.CharField(choices=[('RLL', 'Responsable Local'), ('RLN', 'Responsable National'), ('PASTEUR', 'Pasteur Responsable'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='RLL', max_length=10)),
                ('date_derniere_action', models.DateTimeField(auto_now=True)),
                ('notes_decision', models.TextField(blank=True)),
                ('besoin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='circuit', to='logistque.expressionbesoin')),
            ],
            options={
                'verbose_name': 'Circuit de Validation',
                'verbose_name_plural': 'Circuits de Validation',
            },
        ),
    ]
