# Generated by Django 5.2.3 on 2026-03-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistque', '0005_polecompetence_eglise_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichedefectuosite',
            name='niveau_gravite',
            field=models.CharField(choices=[('Low', 'Faible'), ('Medium', 'Moyen'), ('Critical', 'Critique')], default='Medium', max_length=10),
        ),
    ]
