# Generated by Django 5.2.3 on 2026-03-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistque', '0006_fichedefectuosite_niveau_gravite'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementmateriel',
            name='batch_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de Batch'),
        ),
    ]
