# Generated by Django 5.2.3 on 2026-03-17 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistque', '0007_mouvementmateriel_batch_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thème de Formation',
                'verbose_name_plural': 'Thèmes de Formation',
            },
        ),
        migrations.CreateModel(
            name='DemandeFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_participants', models.PositiveIntegerField(default=1)),
                ('date_souhaitee', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('COMPLETED', 'Réalisée')], default='PENDING', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistque.eglise')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistque.formation')),
            ],
            options={
                'verbose_name': 'Demande de Formation',
                'verbose_name_plural': 'Demandes de Formations',
            },
        ),
        migrations.CreateModel(
            name='SessionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('formateur', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('PLANNING', 'En préparation'), ('CONFIRMED', 'Confirmée'), ('CANCELLED', 'Annulée'), ('COMPLETED', 'Terminée')], default='PLANNING', max_length=20)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistque.formation')),
                ('participants_inscrits', models.ManyToManyField(blank=True, related_name='formations_suivies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de Formation',
                'verbose_name_plural': 'Sessions de Formations',
            },
        ),
    ]
