# Generated by Django 5.2.3 on 2026-03-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistque', '0008_formation_demandeformation_sessionformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressourceformation',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ressourceformation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='formations/thumbnails/'),
        ),
    ]
