# Generated by Django 5.2.3 on 2026-03-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistque', '0009_ressourceformation_date_ajout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='besoin_chronogramme',
            field=models.BooleanField(default=False, verbose_name='Nécessite un chronogramme ?'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='besoin_images',
            field=models.BooleanField(default=False, verbose_name="Nécessite des images d'illustration ?"),
        ),
    ]
