# Generated by Django 5.2.3 on 2026-03-19 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistque', '0010_evenement_besoin_chronogramme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evenements/illustrations/', verbose_name='Image')),
                ('date_ajoutee', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_illustration', to='logistque.evenement', verbose_name='Événement')),
            ],
            options={
                'verbose_name': "Illustration d'Événement",
                'verbose_name_plural': "Illustrations d'Événements",
                'ordering': ['-date_ajoutee'],
            },
        ),
    ]
