# Generated by Django 5.2.3 on 2026-03-20 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistque', '0011_evenementimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronogrammeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('items', models.JSONField(default=list, verbose_name='Items du chronogramme (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronogramme_templates', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Modèle de Chronogramme',
                'verbose_name_plural': 'Modèles de Chronogramme',
                'ordering': ['-created_at'],
            },
        ),
    ]
