# Generated by Django 5.2.3 on 2026-03-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistque', '0012_chronogrammetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='chronogrammetemplate',
            name='headers',
            field=models.JSONField(default=list, verbose_name='En-têtes de colonnes (JSON)'),
        ),
    ]
