# Generated by Django 5.2 on 2026-05-22 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistque', '0013_chronogrammetemplate_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichedefectuosite',
            name='lieu_constat',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu de constat'),
        ),
        migrations.AddField(
            model_name='fichedefectuosite',
            name='nom_materiel_libre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom (matériel non référencé)'),
        ),
        migrations.AlterField(
            model_name='fichedefectuosite',
            name='materiel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_defectuosite', to='logistque.materiel'),
        ),
    ]
