# Generated by Django 5.2.3 on 2025-09-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Adresse email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro de téléphone')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nom')),
                ('last_name', models.CharField(max_length=150, verbose_name='Prénoms')),
                ('role', models.CharField(choices=[('pasteur', 'Pasteur'), ('membre', 'Membre'), ('responsable', 'Responsable')], max_length=20, verbose_name='Rôle')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_images/', verbose_name='Image de profil')),
                ('accept_terms', models.BooleanField(default=False, verbose_name='Accepter les conditions')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'permissions': (('can_view_dashboard', 'Peut accéder au tableau de bord'), ('can_view_users', 'Peut voir les utilisateurs'), ('can_add_user', 'Peut ajouter un utilisateur'), ('can_edit_user', 'Peut éditer un utilisateur'), ('can_delete_user', 'Peut supprimer un utilisateur')),
            },
        ),
    ]
