# Generated by Django 5.2.3 on 2025-08-15 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('logistque', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Adresse email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro de téléphone')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nom')),
                ('last_name', models.CharField(max_length=150, verbose_name='Prénoms')),
                ('role', models.CharField(choices=[('pasteur', 'Pasteur'), ('membre', 'Membre'), ('responsable', 'Responsable')], max_length=20, verbose_name='Rôle')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_images/', verbose_name='Image de profil')),
                ('accept_terms', models.BooleanField(default=False, verbose_name='Accepter les conditions')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('eglise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistque.eglise', verbose_name='Eglise')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
    ]
