# Generated by Django 5.2.3 on 2025-08-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_view_dashboard', 'Peut accéder au tableau de bord'), ('can_view_users', 'Peut voir les utilisateurs'), ('can_add_user', 'Peut ajouter un utilisateur'), ('can_edit_user', 'Peut éditer un utilisateur'), ('can_delete_user', 'Peut supprimer un utilisateur')), 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
    ]
