# Generated by Django 5.2.3 on 2026-03-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super-Administrateur'), ('pasteur_national', 'Pasteur Responsable National'), ('rln', 'Responsable Logistique National (RLN)'), ('pasteur_local', 'Pasteur Responsable Local'), ('rll', 'Responsable Logistique Local (RLL)'), ('technicien', 'Membre Technicien')], max_length=20, verbose_name='Rôle'),
        ),
    ]
