# Generated by Django 5.2.3 on 2026-03-17 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
        ('logistque', '0009_ressourceformation_date_ajout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistque.polecompetence', verbose_name='Pôle Technique'),
        ),
    ]
