# Generated by Django 5.2 on 2026-05-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='user_qr_codes/', verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super-Administrateur'), ('pasteur_national', 'Pasteur Responsable National'), ('rln', 'Responsable Logistique National (RLN)'), ('pasteur_local', 'Pasteur Responsable Local'), ('rll', 'Responsable Logistique Local (RLL)'), ('technicien', 'Membre Technicien'), ('pasteur', 'Pasteur'), ('resp_dept', 'Responsable de Département'), ('adj_dept', 'Adjoint Responsable de Département'), ('resp_sec', 'Responsable de Section'), ('adj_sec', 'Adjoint Responsable de Section'), ('membre_dept', 'Membre de Département'), ('membre_sec', 'Membre de Section')], max_length=20, verbose_name='Rôle'),
        ),
    ]
