# Generated by Django 5.2.3 on 2026-05-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_qr_code_customuser_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super-Administrateur'), ('pasteur_national', 'Pasteur Responsable National'), ('rln', 'Responsable Logistique National (RLN)'), ('pasteur_local', 'Pasteur Responsable Local'), ('rll', 'Responsable Logistique Local (RLL)'), ('technicien', 'Membre Technicien'), ('pasteur', 'Pasteur'), ('resp_dept', 'Responsable de Département'), ('adj_dept', 'Adjoint Responsable de Département'), ('resp_sec', 'Responsable de Section'), ('adj_sec', 'Adjoint Responsable de Section'), ('membre_dept', 'Membre de Département'), ('membre_sec', 'Membre de Section'), ('membre', 'Membre'), ('responsable', 'Responsable')], default='membre', max_length=20, verbose_name='Rôle'),
        ),
    ]
