"""
Django settings for loqt project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from dotenv import load_dotenv
import os
from pathlib import Path

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Security settings
SECRET_KEY = os.environ.get('SECRET_KEY')
DEBUG = os.environ.get('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost,sglci.sajholding.org').split(',')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # Pour la gestion des en-têtes CORS
    'widget_tweaks',
    'accounts',
    'logistque',
    'logistque.events',  # Application pour la gestion des événements et notifications
    'anymail',
    'django_htmx',
    'rest_framework',
    'django_filters',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Doit être placé avant CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'logistque.middleware.LoggingMiddleware',
]

ROOT_URLCONF = 'loqt.urls'
AUTH_USER_MODEL = 'accounts.CustomUser'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'logistque.context_processors.static_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'loqt.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DB_NAME', BASE_DIR / 'db.sqlite3' if os.environ.get('DB_ENGINE') == 'django.db.backends.sqlite3' else 'loqt'),
        'USER': os.environ.get('DB_USER', 'loqt'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'loqt264'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Configuration des logs
_LOG_LEVEL = os.environ.get('DJANGO_LOGLEVEL', 'INFO').upper() or 'INFO'
_USE_FILE_HANDLER = not os.environ.get('DOCKER', False) and not os.environ.get('KUBERNETES_SERVICE_HOST')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': _LOG_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        **({
            'file': {
                'level': 'DEBUG',
                'class': 'logging.FileHandler',
                'filename': os.path.join(BASE_DIR, 'debug.log'),
                'formatter': 'verbose',
            },
        } if _USE_FILE_HANDLER else {}),
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'] if _USE_FILE_HANDLER else ['console'],
            'level': _LOG_LEVEL,
            'propagate': True,
        },
        'logistque': {
            'handlers': ['file', 'console'] if _USE_FILE_HANDLER else ['console'],
            'level': _LOG_LEVEL,
            'propagate': True,
        },
        'accounts': {
            'handlers': ['file', 'console'] if _USE_FILE_HANDLER else ['console'],
            'level': _LOG_LEVEL,
            'propagate': True,
        },
    },
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'fr-FR'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'static_dev',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise configuration
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_IGNORE_MISSING_FILES = True

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email backend
# Email backend
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'webmaster@localhost')

# Login URL
LOGIN_URL = '/' # Redirige vers la racine (géré par React ou Nginx)
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

# Security settings
# Configuration pour les requêtes derrière un proxy
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# En production, ALLOWED_HOSTS doit provenir de l'env (voir plus haut).
# En développement, le bloc DEBUG ci-dessous forcera ALLOWED_HOSTS=['*'].

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Configuration des origines CSRF et CORS
CSRF_TRUSTED_ORIGINS = [
    "http://localhost",
    "http://localhost:5173",
    "http://127.0.0.1",
    "http://127.0.0.1:5173",
    "https://*.ngrok-free.app",
    "https://*.ngrok.io",
    "https://sglci.sajholding.org",
    "https://www.sglci.sajholding.org",
]

# Configuration CORS pour les requêtes cross-origin
CORS_ALLOW_ALL_ORIGINS = False  # Désactiver l'accès depuis toutes les origines pour plus de sécurité
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://sglci.sajholding.org",   # Production
    "https://www.sglci.sajholding.org",  # Production avec www
    "http://localhost:3000",         # React développement
    "http://localhost:5173",         # Vite développement local
    "http://127.0.0.1:3000",         # React développement local
    "http://127.0.0.1:5173",         # Vite développement local (127.0.0.1)
    "http://localhost:8000",         # Développement local Django
    "http://127.0.0.1:8000",         # Développement local Django
    "https://*.sajholding.org",      # Sous-domaines
    "https://*.ngrok-free.app",       # Pour le tunneling local
    "https://*.ngrok.io",             # Pour le tunneling local
]

# Autoriser les en-têtes personnalisés
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Méthodes HTTP autorisées
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Désactiver la vérification du host header en développement
if DEBUG:
    import socket
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + ["127.0.0.1", "10.0.2.2"]
    
    # Désactiver la vérification du host header en développement
    ALLOWED_HOSTS = ['*']
    
    # CORS settings pour le développement
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOW_ALL_HEADERS = True
    CORS_ALLOW_ALL_METHODS = True
    
    # Désactiver la vérification CSRF en développement
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False

# Security headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# HSTS settings
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Session settings
SESSION_COOKIE_SECURE = True  # Obligatoire pour SameSite=None
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'None'

# CSRF settings
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = False  # Permettre au frontend de lire le token si nécessaire
CSRF_COOKIE_SAMESITE = 'None'



# CORS settings (if needed) - déjà défini plus haut; éviter les doublons

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# Configuration pour django-import-export
IMPORT_EXPORT_USE_TRANSACTIONS = True  # Utiliser des transactions pour les imports
IMPORT_EXPORT_SKIP_ADMIN_LOG = False  # Ne pas enregistrer les logs d'import/export dans l'historique admin
IMPORT_EXPORT_IMPORT_PERMISSION_CODE = 'add'  # Permission requise pour effectuer des imports
IMPORT_EXPORT_EXPORT_PERMISSION_CODE = 'view'  # Permission requise pour effectuer des exports
IMPORT_FORMATS = [
    'xlsx',
    'xls',
    'csv',
    'json',
    'yaml',
    'html',
    'tsv',
    'ods'
]
